name: Release Project

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, linux, linux]
        arch: [amd64, amd64, arm64, arm]
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: windows
            arch: amd64
            suffix: windows-amd64.exe
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: linux
            arch: arm
            suffix: linux-arm

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o restaurant_app-${{ matrix.suffix }}

          sha256sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha256
          sha512sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha512

          mkdir build
          cp restaurant_app-${{ matrix.suffix }} build/
          cp restaurant_app-${{ matrix.suffix }}.sha256 build/
          cp restaurant_app-${{ matrix.suffix }}.sha512 build/
          echo "Thanks for downloading! Verify with the provided checksums." > build/README.txt

          zip -r restaurant_app-${{ matrix.suffix }}.zip build/*

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: restaurant_app-${{ matrix.suffix }}.zip
          token: ${{ secrets.GH_TOKEN }}
