name: Release Project

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o restaurant_app-${{ matrix.suffix }}
          sha256sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha256
          sha512sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha512

      - name: Upload artifact for deploy
        uses: actions/upload-artifact@v4
        with:
          name: linux-amd64-binary
          path: restaurant_app-linux-amd64

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            restaurant_app-${{ matrix.suffix }}
            restaurant_app-${{ matrix.suffix }}.sha256
            restaurant_app-${{ matrix.suffix }}.sha512
          token: ${{ secrets.GH_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-amd64-binary

      - name: List downloaded files
        run: ls -R

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: restaurant_app-linux-amd64
          target: /opt

      - name: Restart systemd service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo chmod +x /opt/aurant_app-linux-amd64
            sudo systemctl restart restaurantapp
