name: Release Project

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: linux
            arch: arm
            suffix: linux-arm
          - os: windows
            arch: amd64
            suffix: windows-amd64.exe

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Build for ${{ matrix.os }}-${{ matrix.arch }}
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o restaurant_app-${{ matrix.suffix }}

          sha256sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha256
          sha512sum restaurant_app-${{ matrix.suffix }} > restaurant_app-${{ matrix.suffix }}.sha512

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            restaurant_app-${{ matrix.suffix }}
            restaurant_app-${{ matrix.suffix }}.sha256
            restaurant_app-${{ matrix.suffix }}.sha512
          token: ${{ secrets.GH_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event.release.tag_name != ''
    steps:
      - name: Download release asset (linux-amd64)
        uses: actions/download-artifact@v4
        with:
          name: restaurant_app-linux-amd64

      - name: Deploy to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: restaurant_app-linux-amd64
          target: /opt/${{ secrets.SERVER_USER }}/restaurant_app

      - name: Run app on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            systemctl restart restaurantapp
